# Generated by Django 5.1.2 on 2024-11-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_newsmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
