# Generated by Django 5.1.2 on 2024-11-08 11:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_newsmodel_is_active_newsmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
